version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    reviewers:
      - "Fadil369"
    assignees:
      - "Fadil369"
    commit-message:
      prefix: "security"
      include: "scope"
    allow:
      - dependency-type: "all"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 15
    reviewers:
      - "Fadil369"
    assignees:
      - "Fadil369"
    commit-message:
      prefix: "security"
      include: "scope"
    allow:
      - dependency-type: "all"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10