name = "tawnia-healthcare-analytics"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

[build]
command = "npm run build"

[build.upload]
format = "modules"

[[pages_config]]
production_branch = "main"