name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Node dependencies
      run: npm ci --audit-level=none
    
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    
    - name: Run npm audit
      run: npm audit --audit-level=high --production
      continue-on-error: true
    
    - name: Run Python security check
      run: |
        pip install safety==3.2.4 bandit==1.7.9
        safety check --json --output safety-report.json || true
        bandit -r src/ -f json -o bandit-report.json || true
    
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: auto
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json